from abc import ABC, abstractmethod


from ..utils.models import Container
from ..utils.keygen import KeyGenerator


class BaseContainerRepository(ABC):
    """A base class for managing container parameters stored in persistent storage"""
    
    @abstractmethod
    def __init__(self, key_generator: KeyGenerator) -> None:
        """
        Initializes the repository. Subdomains will be generated by `key_generator`.

        Args:
            key_generator: Class generating unique strings. 
        """
        self.key = key_generator
    

    @abstractmethod
    def create(self, ip: str, port: int) -> str:
        """
        Creates a new container record.

        Args:
            ip: The IP address of the host running the container.
            port: The port exposed by the container.

        Returns:
            str: The generated subdomain for the container.

        Raises:
            RuntimeError: If creation fails.
        """
        ...
    
    @abstractmethod
    def read(self, subdomain: str) -> tuple[str, int]:
        """
        Retrieves container details by subdomain.

        Args:
            subdomain: The subdomain to look up.

        Returns:
            tuple[str, int]: A tuple containing (host_ip, port).

        Raises:
            KeyError: If the container does not exist.
        """
        ...
    
    @abstractmethod
    def delete(self, subdomain: str) -> None:
        """
        Removes the container with specified subdomain.

        Args:
            subdomain: The subdomain of the container to remove.
        
        Raises:
            KeyError: If the container does not exist.
        """
        ...
    
    def dict(self) -> list[dict[str, str]]:
        """
        Returns all stored containers in JSON friendly format.

        Returns:
             list[dict[str, str]]: List of container dictionaries.
        """
        ...



class SQLContainerRepository(BaseContainerRepository):
    """
    Implementation of storage using Peewee ORM.
    """

    def __init__(self, key_generator: KeyGenerator) -> None:
        query = Container.select(Container.subdomain)
        keys = [c.subdomain for c in query]
        key_generator.load(keys)
        super().__init__(key_generator)
        
         
    def create(self, ip: str, port: int) -> str:
        try:
            new_key = self.key.gen()
            container: Container = Container.create(
                subdomain=new_key,
                host=ip,
                port=port
            )
            return str(container.subdomain)
        except Exception as e:
            raise RuntimeError(f"failed to create container {ip}:{port}: {e}")
        

    def read(self, subdomain: str) -> tuple[str, int]:
        query = (Container
                    .select(Container.host, Container.port)
                    .where(Container.subdomain == subdomain))
        
        if not query.exists():
            raise KeyError(f"container {subdomain} does not exist")
        
        return query[0].host.ip, query[0].port
    

    def delete(self, subdomain: str) -> None:
        query = (Container
                    .delete()
                    .where(Container.subdomain == subdomain))
        
        rows_deleted = query.execute()
        
        if rows_deleted == 0:
            raise KeyError(f"container {subdomain} does not exist")
        

    def dict(self) -> list[dict[str, str]]:

        query = Container.select()
        return [{
                "subdomain": c.subdomain, 
                "ip": c.host_id,
                "port": str(c.port)
            } for c in query
        ]