from abc import ABC, abstractmethod


from ..utils.models import Container
from ..utils.keygen import KeyGenerator


class BaseContainerRepository(ABC):
    """A base class for managing container parameters stored in persistent storage"""
    
    @abstractmethod
    def __init__(self, key_generator: KeyGenerator) -> None:
        """
        Initializes the repository. Subdomains will be generated by `key_generator`.

        Args:
            key_generator: Class generating unique strings. 
        """
        self.key = key_generator
    

    @abstractmethod
    def create(self, ip: str, port: int, config_json: str) -> str:
        """
        Creates a new container record.

        Args:
            ip: The IP address of the host running the container.
            port: The port exposed by the container.
            config_json: Serialized ComposeConfig (JSON) to persist for deferred deployment.

        Returns:
            str: The generated subdomain for the container.

        Raises:
            RuntimeError: If creation fails.
        """
        ...

    @abstractmethod
    def read(self, **filters) -> list[Container]:
        """
        Retrieves container records matching the given filters.

        Args:
            **filters: Field names and values to filter by (e.g. subdomain="abc",
                       to_be_deleted=True, host="1.2.3.4").

        Returns:
            list[Container]: Matching Container model instances.
        """
        ...
    
    @abstractmethod
    def update(self, subdomain: str, **fields) -> None:
        """
        Updates arbitrary fields on a container record.

        Args:
            subdomain: The subdomain of the container.
            **fields: Field names and their new values.

        Raises:
            KeyError: If the container does not exist.
        """
        ...

    @abstractmethod
    def delete(self, subdomain: str) -> None:
        """
        Removes the container with specified subdomain.

        Args:
            subdomain: The subdomain of the container to remove.
        
        Raises:
            KeyError: If the container does not exist.
        """
        ...

    def list(self) -> list[dict[str, str]]:
        """
        Returns all stored containers in JSON friendly format.

        Returns:
             list[dict[str, str]]: List of container dictionaries.
        """
        ...



class SQLContainerRepository(BaseContainerRepository):
    """
    Implementation of storage using Peewee ORM.
    """

    def __init__(self, key_generator: KeyGenerator) -> None:
        query = Container.select(Container.subdomain)
        keys = [c.subdomain for c in query]
        key_generator.load(keys)
        super().__init__(key_generator)
        
         
    def create(self, ip: str, port: int, config_json: str) -> str:
        try:
            new_key = self.key.gen()
            container: Container = Container.create(
                subdomain=new_key,
                host=ip,
                port=port,
                config=config_json,
            )
            return str(container.subdomain)
        except Exception as e:
            raise RuntimeError(f"failed to create container {ip}:{port}: {e}")


    def read(self, **filters) -> list[Container]:
        query = Container.select()
        for field, value in filters.items():
            query = query.where(getattr(Container, field) == value)
        return list(query)
    

    def update(self, subdomain: str, **fields) -> None:
        rows = (Container
                    .update(**fields)
                    .where(Container.subdomain == subdomain)
                    .execute())
        if rows == 0:
            raise KeyError(f"container {subdomain} does not exist")
    
    
    def delete(self, subdomain: str) -> None:
        query = (Container
                    .delete()
                    .where(Container.subdomain == subdomain))
        
        rows_deleted = query.execute()
        
        if rows_deleted == 0:
            raise KeyError(f"container {subdomain} does not exist")


    def list(self) -> list[dict[str, str]]:

        query = Container.select()
        return [{
                "subdomain": row.subdomain, 
                "ip": row.host_id,
                "port": str(row.port),
                "to_be_deleted": row.to_be_deleted,
                "initialized": row.initialized,
                "config": row.config
            } for row in query]